
%% Paths for local run
% BRANT and SPM may need
%    sudo xattr -dr com.apple.quarantine <path>
addpath([pwd '/../../external/brant/brant-stable']);
brant_configure_paths;
brant_configure_paths([pwd '/../../external/spm12_r7771/spm12']);


%% Input images and output dir
fmri_nii = [pwd '/../../INPUTS/fmri.nii'];
fmri_json = [pwd '/../../INPUTS/fmri.json'];
t1_nii = [pwd '/../../INPUTS/t1.nii'];
t1_json = [pwd '/../../INPUTS/t1.json'];
out_dir = [pwd '/../../OUTPUTS'];


%% Copy files to work dir and get scan-specific information
copyfile(fmri_nii,fullfile(out_dir,'fmri.nii'));
copyfile(fmri_json,fullfile(out_dir,'fmri.json'));
copyfile(t1_nii,fullfile(out_dir,'t1.nii'));
copyfile(t1_json,fullfile(out_dir,'t1.json'));

fid = fopen(fullfile(out_dir,'fmri.json'), 'r');
jstr = fread(fid, '*char').';
fclose(fid);
fmri_info = jsondecode(jstr);

fmri_trsec = fmri_info.RepetitionTime;
fprintf('Found TR = %0.3f sec for %s\n',fmri_trsec,fmri_nii);


%% Configure BRANT variables for preprocessing
batch_file = fullfile(out_dir,'brant_Preprocessing.mat');
gui_fn = 'brant_Preprocessing';
gui_func = @brant_preprocess_jobman;
gui_version = '3.37';

% Initialize
clear gui_parameters

% Inputs
gui_parameters{1}.subj.text.inputfile = '';
gui_parameters{1}.subj.text.dirs = '';
gui_parameters{1}.subj.spm.dirs = {out_dir};  % fmri input file dir
gui_parameters{1}.subj.filetype = 'fmri.nii';  % fmri filename pattern
gui_parameters{1}.subj.is4d = 1;
gui_parameters{1}.subj.out.selected = 0;
gui_parameters{1}.subj.out.dir = out_dir;  % called wkdir in GUI
gui_parameters{1}.subj.out.nmpos = 1;  % Frame within nifti?

% Options
gui_parameters{1}.pref = struct( ...
    'parallel','off', ...
    'parallel_workers',1, ...
    'sync',1, ...  % 1 to force match TR between slice timing, denoise
    'order',{{'slicetiming' 'realign' 'coregister' 'normalise12' 'denoise' 'smooth'}}, ...
    'dirs_in_text',0, ...
    'norm12_ind',1 ...
    );

% Preprocessing steps
gui_parameters{1}.ind = struct( ...
    'slicetiming',0, ...
    'realign',1, ...
    'coregister',1, ...
    'normalise',0, ...
    'normalise12',1, ...
    'denoise',1, ...
    'smooth',0 ...
    );

% Slice timing
%% FIXME Need slice timing params here matching the data
gui_parameters{1}.slicetiming = struct( ...
    'slice_order',0, ...
    'tr',fmri_trsec, ...
    'refslice',0, ...
    'prefix','a' ...
    );

% Realign
gui_parameters{1}.realign.eoptions = struct( ...
    'quality',0.9000, ...
    'sep',4, ...
    'fwhm',5, ...
    'rtm',1, ...
    'wrap',[0 0 0], ...
    'interp',4 ...
    );
gui_parameters{1}.realign.roptions = struct( ...
    'which',[2 1], ...
    'interp',4, ...
    'wrap',[0 0 0], ...
    'mask',1, ...
    'prefix','r' ...
    );

% Coregister
gui_parameters{1}.coregister.subj = struct( ...
    'filetype_ref','meanfmri.nii', ...
    'filetype_src','t1.nii', ...
    'seg_bet_ind',1 ...
    );
gui_parameters{1}.coregister.eoptions = struct( ...
    'cost_fun','nmi', ...
    'sep',[4 2], ...
    'tol',[0.0200 0.0200 0.0200 1.0000e-03 1.0000e-03 1.0000e-03 0.0100 0.0100 0.0100 1.0000e-03 1.0000e-03 1.0000e-03], ...
    'fwhm',[7 7] ...
    );

% Old normalise
gui_parameters{1}.normalise.subj = struct( ...
    'filetype_src','meanfmri.nii', ...
    'filetype_wt','' ...
    );
gui_parameters{1}.normalise.eoptions = struct( ...
    'template',[spm('Dir') '/toolbox/OldNorm/EPI.nii'], ...
    'weight','', ...
    'smosrc',8, ...
    'smoref',0, ...
    'regtype','mni', ...
    'cutoff',25, ...
    'nits',30, ...
    'reg',1 ...
    );
gui_parameters{1}.normalise.roptions = struct( ...
    'preserve',0, ...
    'bb',[-90 -126 -72; 90 90 108], ...
    'vox',[3 3 3], ...
    'interp',5, ...
    'wrap',[0 0 0], ...
    'prefix','w' ...
    );

% SPM12 normalise
gui_parameters{1}.normalise12.subj = struct( ...
    'filetype_src','meanfmri.nii' ...
    );
gui_parameters{1}.normalise12.eoptions = struct( ...
    'biasreg',1.0000e-04, ...
    'biasfwhm',60, ...
    'tpm',[spm('Dir') '/tpm/TPM.nii'], ...
    'affreg','mni', ...
    'reg',[0 1.0000e-03 0.5000 0.0500 0.2000], ...
    'fwhm',0, ...
    'samp',3 ...
    );
gui_parameters{1}.normalise12.woptions = struct( ...
    'bb',[-90 -126 -72; 90 90 108], ...
    'vox',[3 3 3], ...
    'interp',4, ...
    'prefix','w' ...
    );

% Denoise
gui_parameters{1}.denoise.space_mask = struct( ...
    'space_comm',1, ...
    'space_ind',0, ...
    'mask_res_type','nearest neighbour', ...
    'ft_motion','rp_fmri.txt' ...
    );
gui_parameters{1}.denoise.space_mask.mask_wb = struct( ...
    'ind',1, ...
    'string',[fileparts(which('brant')) '/template/mask_ICV_WB.nii.gz'] ...
    );
gui_parameters{1}.denoise.space_mask.mask_gs = struct( ...
    'ind',1, ...
    'string',[fileparts(which('brant')) '/template/mask_ICV_WB.nii.gz'] ...
    );
gui_parameters{1}.denoise.space_mask.mask_wm = struct( ...
    'ind',1, ...
    'string',[fileparts(which('brant')) '/template/mask_WM.nii.gz'] ...
    );
gui_parameters{1}.denoise.space_mask.mask_csf = struct( ...
    'ind',1, ...
    'string',[fileparts(which('brant')) '/template/mask_CSF.nii.gz'] ...
    );
gui_parameters{1}.denoise.space_mask.ft_wb = struct( ...
    'ind',1, ...
    'string','wholebrain.nii', ...
    'thr',0.8000 ...
    );
gui_parameters{1}.denoise.space_mask.ft_gs = struct( ...
    'ind',1, ...
    'string','c1t1.nii', ...
    'thr',0.8000 ...
    );
gui_parameters{1}.denoise.space_mask.ft_wm = struct( ...
    'ind',1, ...
    'string','c2t1.nii', ...
    'thr',0.8000 ...
    );
gui_parameters{1}.denoise.space_mask.ft_csf = struct( ...
    'ind',1, ...
    'string','c3t1.nii', ...
    'thr',0.8000 ...
    );
gui_parameters{1}.denoise.reg_mdl = struct( ...
    'lin_trend',1, ...
    'quad_trend',0, ...
    'char_info','T(selected tissue): GS,WM,CSF↵R(motion): x,y,z,pitch,roll,yaw', ...
    'spike_info','\nSpike Handling', ...
    'scrubbing',0, ...
    'fd_thr',0.5000 ...
    );
% T = WM, CSF, global, etc
% R = movement
% square = param ^ 2
% prime = param first difference
% prep = param lagged 1 frame
gui_parameters{1}.denoise.reg_mdl.regressors = struct( ...
    'T',1, ...
    'T_square',0, ...
    'T_prime',1, ...
    'T_prime_square',0, ...
    'T_prep',0, ...
    'T_prep_square',0, ...
    'R',1, ...
    'R_square',1, ...
    'R_prime',1, ...
    'R_prime_square',1, ...
    'R_prep',0, ...
    'R_prep_square',0 ...
    );
gui_parameters{1}.denoise.fil_opt = struct( ...
    'tr',fmri_trsec, ...
    'lower_cutoff',0.0100, ...
    'upper_cutoff',0.0800, ...
    'opt','\nOutput Options', ...
    'reg_filter',1, ...
    'filter_reg',0, ...
    'reg_only',0, ...
    'filter_only',0, ...
    'save_last',0, ...
    'gzip_output',0, ...
    'gsr_nogsr',1, ...
    'prefix_reg','d', ...
    'prefix_filter','f' ...
    );

% Smooth
gui_parameters{1}.smooth = struct( ...
    'fwhm',[6 6 6], ...
    'prefix','s6', ...
    'dtype',0, ...
    'im',1 ...
    );

% Save to file
save(batch_file,'gui_fn','gui_func','gui_version','gui_parameters');

% Run
gui_func(gui_parameters{:},[]);
